### ISSUE TITLE
Draft of 03_Loading_and_visualizing_models

### ISSUE THREAD

**Issue by aleaf** [DOI-USGS/python-for-hydrology#24]
Hey @jlarsen-usgs, I've got a draft of the 03_Loading_and_visualizing_models lesson [here](https://github.com/aleaf/python-for-hydrology/blob/main/notebooks/part1_flopy/03_Loading_and_visualizing_models.ipynb). Would you mind taking a look and providing any feedback? Just want to make sure I don't miss anything important. In particular, not sure if I got the obs output stuff right. This statement: ``#m.obs_3.output.obs()`` resulted in an error, i think due to having multiple head obs with the same name (my approach recently has been to populate each layer at a location with an obs, and then to postprocess the results after the model run to a simulated equivalent reflecting the transmissivity-weighted avg. for the open interval). Wondering if it might be easier at this point to just demonstrate that the head obs output file can be opened by pandas.

Thanks!

**Comment by mnfienen** [comment]
I think we got this sorted out
