### ISSUE TITLE
Suppress warnings/errors within notebooks

### ISSUE THREAD

**Issue by jlarsen-usgs** [DOI-USGS/python-for-hydrology#67]
Notebooks that have been checked in after being run and display a warning, error message, or other path as output should either be cleared or have that output suppressed if it includes an absolute path. This is a FSP requirement for publication as absolute system paths can be considered sensitive information.

**Comment by mnfienen** [comment]
right on - we should be able to make sure they are all cleared when committing. thanks @jlarsen-usgs

**Comment by mnfienen** [comment]
added a `clear_all_notebooks.py` script to `notebooks` that will simply remove all output
